name: Grep-Output

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Identify errors
      run: grep 'Error.  ' $GITHUB_WORKSPACE/sarif/superlinter-output.txt > superlinter-issues.txt

    - name: Iterate through errors
      run: |
        cat superlinter-issues.txt | while read line || [[ -n $line ]];
        do
          echo 'Line: ' $line
          IFS=':'; arrLine=($line); unset IFS;
          echo '  Split_length' ${#arrLine[@]}
          echo '  Split_0' ${arrLine[0]}
          echo '  Split_1' ${arrLine[1]}
          echo '  Split_2' ${arrLine[2]}
          echo '  Split_3' ${arrLine[3]}
        done