name: Grep-Output

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Identify errors
      run: grep 'Error.  ' $GITHUB_WORKSPACE/sarif/superlinter-output.txt > superlinter-issues.txt

    - name: Iterate through errors
      run: |
        cat superlinter-issues.txt | while read line || [[ -n $line ]];
        do
          echo 'Line: ' $line
          IFS=':'; arrLine=($line); unset IFS;
          echo '  Length' ${#arrLine[@]}
          for i in "${arrLine[@]}"
          do
            echo '    ' $i
          done
        done