name: Grep-Output

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Identify errors
      run: grep 'Error.  ' $GITHUB_WORKSPACE/sarif/superlinter-output.txt > superlinter-issues.txt

    - name: Iterate through errors and create SARIF json file
      run: |
        echo '##############################################################'
        echo '{' > sarif-superlinter.json
        echo '    "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",' >> sarif-superlinter.json
        echo '    "version": "2.1.0",' >> sarif-superlinter.json
        echo '    "runs": [' >> sarif-superlinter.json
        echo '      {' >> sarif-superlinter.json
        echo '        "tool": {' >> sarif-superlinter.json
        echo '          "driver": {' >> sarif-superlinter.json
        echo '##############################################################'
        cat superlinter-issues.txt | while read line || [[ -n $line ]];
        do
#          echo 'Line: ' $line
#          IFS=':'; arrLine=($line); unset IFS;
#          echo '  Length' ${#arrLine[@]}
#          for i in "${arrLine[@]}"
#          do
#            echo '    ' $i
#          done
        done
        echo '##############################################################'
        cat sarif-superlinter.json