name: Super-Linter

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Lint
      uses: github/super-linter@v3
      env:
        DEFAULT_BRANCH: develope
        VALIDATE_JAVA: true
        OUTPUT_FORMAT: tap
        OUTPUT_DETAILS: detailed
        LOG_FILE: superlinter.txt
        DISABLE_ERRORS: true
        
    - name: Check lint output
      run: cat $GITHUB_WORKSPACE/superlinter.txt
